version: '3'
networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/16
          gateway: 172.0.0.254
          ip_range: 172.0.0.0/24

services:
  my_app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    networks:
      my_network:
        ipv4_address: 172.0.0.1

  my_app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
    networks:
      my_network:
        ipv4_address: 172.0.0.2

  my_app3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
    networks:
      my_network:
        ipv4_address: 172.0.0.3

  my_app4:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - PORT=8084
    networks:
      my_network:
        ipv4_address: 172.0.0.4

  my_app5:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
    networks:
      my_network:
        ipv4_address: 172.0.1.5
